using Azure;
using Azure.AI.DocumentIntelligence;
using Azure.Core;
using Azure.Identity;
using MarkItDown.Core;
using MarkItDown.Core.Converters;
using MarkItDown.Core.Models;
using System.Text.RegularExpressions;

namespace MarkItDown.Azure;

/// <summary>
/// Converts documents using Azure AI Document Intelligence (prebuilt-layout model).
/// Must be registered manually — not included in the default built-in converters.
/// </summary>
public sealed partial class DocumentIntelligenceConverter : DocumentConverter
{
    private static readonly HashSet<string> SupportedExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".pdf", ".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif",
        ".docx", ".pptx", ".xlsx", ".html", ".htm"
    };

    private static readonly HashSet<string> NoOcrExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".docx", ".pptx", ".xlsx", ".html", ".htm"
    };

    private readonly DocumentIntelligenceClient _client;

    public DocumentIntelligenceConverter(string endpoint, AzureKeyCredential credential)
    {
        _client = new DocumentIntelligenceClient(new Uri(endpoint), credential);
    }

    public DocumentIntelligenceConverter(string endpoint, TokenCredential credential)
    {
        _client = new DocumentIntelligenceClient(new Uri(endpoint), credential);
    }

    public DocumentIntelligenceConverter(string endpoint)
    {
        var apiKey = Environment.GetEnvironmentVariable("AZURE_API_KEY");
        if (apiKey is not null)
            _client = new DocumentIntelligenceClient(new Uri(endpoint), new AzureKeyCredential(apiKey));
        else
            _client = new DocumentIntelligenceClient(new Uri(endpoint), new DefaultAzureCredential());
    }

    public override bool Accepts(Stream stream, StreamInfo streamInfo)
    {
        var ext = streamInfo.Extension?.ToLowerInvariant();
        if (ext is not null && SupportedExtensions.Contains(ext)) return true;

        var mime = streamInfo.MimeType?.ToLowerInvariant() ?? "";
        return mime.StartsWith("application/pdf") ||
               mime.StartsWith("image/jpeg") ||
               mime.StartsWith("image/png") ||
               mime.StartsWith("image/bmp") ||
               mime.StartsWith("image/tiff") ||
               mime.StartsWith("application/vnd.openxmlformats-officedocument") ||
               mime.StartsWith("text/html") ||
               mime.StartsWith("application/xhtml");
    }

    public override async Task<DocumentConverterResult> ConvertAsync(
        Stream stream,
        StreamInfo streamInfo,
        MarkItDownConversionContext context,
        CancellationToken cancellationToken = default)
    {
        var ext = streamInfo.Extension?.ToLowerInvariant();
        bool noOcr = NoOcrExtensions.Contains(ext ?? "");

        var content = BinaryData.FromStream(stream);

        var options = new AnalyzeDocumentOptions("prebuilt-layout", content)
        {
            OutputContentFormat = DocumentContentFormat.Markdown,
        };

        if (!noOcr)
        {
            options.Features.Add(DocumentAnalysisFeature.Formulas);
            options.Features.Add(DocumentAnalysisFeature.OcrHighResolution);
            options.Features.Add(DocumentAnalysisFeature.FontStyling);
        }

        var operation = await _client.AnalyzeDocumentAsync(WaitUntil.Completed, options, cancellationToken);
        var result = operation.Value;

        // Strip HTML comments generated by Document Intelligence
        var markdown = HtmlCommentRegex().Replace(result.Content ?? "", "");
        return new DocumentConverterResult(markdown);
    }

    [GeneratedRegex(@"<!--.*?-->", RegexOptions.Singleline)]
    private static partial Regex HtmlCommentRegex();
}
